server:
    port: 8081

spring:
    application:
        name: zaplink-shortner-service
    # DataSource config
    datasource:
        url: jdbc:postgresql://localhost:5432/zaplink_core
        username: postgres
        password: 12345
    # JPA config
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect

#Custom properties
base.url: http://localhost:8090/r/