apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'zaplink-spring-boot'
        metrics_path: /actuator/prometheus
        static_configs:
          - targets:
              - api-gateway-service:8090
              - zaplink-shortner-service:8081
              - zaplink-processor-service:8082
              - zaplink-manager-service:8083
              - zaplink-auth-service:8084
              - zaplink-notification-service:8085