server:
    port: 8085
    context-path: /v1

spring:
    application:
        name: zaplink-notification-service
    # Mail config
    mail:
        host: smtp.gmail.com
        port: 587
        username: tech.dustbiin@gmail.com
        password: vouhivqwwjgcbuem
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
    # Kafka config
    kafka:
        bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
        consumer:
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
            auto-offset-reset: earliest
        properties:
            spring.json.use.type.headers: false
            spring.json.trusted.packages: "*"
            spring.json.value.default.type: "io.zaplink.notification.dto.request.EmailRequest"
