server:
    port: 8082
    servlet:
        context-path: /api/v1

spring:
    application:
        name: zaplink-processor-service
    # Kafka config
    kafka:
        group-id: zaplink-consumer-group
        auto-offset-reset: earliest
        bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
        consumer:
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        properties:
            spring.json.trusted.packages: "*"
            spring.json.use.type.headers: false
            # spring.json.value.default.type: io.zaplink.zaplink_consumer_service.dto.request.ShortUrlConsumerRequest
    # Redis config
    data:
        redis:
            host: ${SPRING_DATA_REDIS_HOST:redis}
            port: ${SPRING_DATA_REDIS_PORT:6379}

eureka:
    client:
        serviceUrl:
            # defaultZone: http://localhost:8761/eureka/
            defaultZone: http://zaplink-service-registry:8761/eureka/
