server:
    port: 8082

spring:
    application:
        name: zaplink-processor-service
    # Kafka config
    kafka:
        bootstrap-servers: localhost:9092
        consumer:
            auto-offset-reset: earliest
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        properties:
            "[spring.json.trusted.packages]": "*"
            "[spring.json.use.type.headers]": "true"
            "[spring.json.type.mapping]": "io.zaplink.manager.dto.request.ClickCount:io.zaplink.processor.dto.request.ClickCount"
    # Redis config
    data:
        redis:
            host: localhost
            port: 6379
    # DataSource config
    datasource:
        url: jdbc:postgresql://localhost:5432/zaplink_core
        username: postgres
        password: 12345
    # JPA config
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect

# Batch Processing Configuration
zaplink:
    batch:
        flush-interval: 15000  # Flush every 5 seconds (5000ms)