apiVersion: apps/v1
kind: Deployment
metadata:
    name: api-gateway-service
    labels:
        app: api-gateway-service
spec:
    replicas: 1
    selector:
        matchLabels:
            app: api-gateway-service
    template:
        metadata:
            labels:
                app: api-gateway-service
        spec:
            containers:
                - name: api-gateway-service
                  image: api-gateway-service:latest
                  imagePullPolicy: Never
                  ports:
                      - containerPort: 8090
                  env:
                      - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
                        value: "http://zaplink-service-registry:8761/eureka/"
                      - name: SPRING_PROFILES_ACTIVE
                        value: "k8s"
---
apiVersion: v1
kind: Service
metadata:
    name: api-gateway-service
spec:
    selector:
        app: api-gateway-service
    ports:
        - port: 8090
          targetPort: 8090
    type: NodePort
