apiVersion: apps/v1
kind: Deployment
metadata:
    name: api-gateway-service
    labels:
        app: api-gateway-service
spec:
    replicas: 1
    selector:
        matchLabels:
            app: api-gateway-service
    template:
        metadata:
            labels:
                app: api-gateway-service
        spec:
            containers:
                - name: api-gateway-service
                  image: api-gateway-service:latest
                  imagePullPolicy: Never
                  ports:
                      - containerPort: 8090
                  env:
                      - name: SPRING_PROFILES_ACTIVE
                        value: "k8s"
                        startupProbe:
                          httpGet:
                            path: /actuator/health/liveness
                            port: 8090
                          initialDelaySeconds: 10
                          timeoutSeconds: 5
                          failureThreshold: 60
                          periodSeconds: 10

                        livenessProbe:
                          httpGet:
                            path: /actuator/health/liveness
                            port: 8090
                          timeoutSeconds: 5
                          initialDelaySeconds: 60
                          periodSeconds: 15

                        readinessProbe:
                          httpGet:
                            path: /actuator/health/readiness
                            port: 8090
                          timeoutSeconds: 5
                          initialDelaySeconds: 45
                          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
    name: api-gateway-service
spec:
    selector:
        app: api-gateway-service
    ports:
        - port: 8090
          targetPort: 8090
    type: NodePort
