resources:
  - redis-storage.yml
  - kafka-storage.yml
  - postgres-storage.yml
  - zaplink-config.yml
  - api-gateway-deployment.yaml
  - zaplink-manager-deployment.yaml
  - zaplink-processor-deployment.yaml
  - zaplink-core-deployment.yaml
  - zaplink-auth-deployment.yaml
  - zaplink-notification-deployment.yaml
  - redis-deployment.yaml
  - kafka-deployment.yaml
  - kafka-ui-deployment.yaml
  - postgres-deployment.yaml
  - /prometheus/prometheus-config.yaml
  - /prometheus/prometheus-deployment.yaml
  - /prometheus/prometheus-service.yaml
  - /grafana/grafana-datasources-config.yaml
  - /grafana/grafana-deployment.yaml
  - /grafana/grafana-service.yaml