resources:
  - redis-storage.yml
  - kafka-storage.yml
  - zaplink-config.yml
  - api-gateway-deployment.yaml
  - zaplink-manager-deployment.yaml
  - zaplink-processor-deployment.yaml
  - zaplink-shortner-deployment.yaml
  - redis-deployment.yaml
  - kafka-deployment.yaml
  - kafka-ui-deployment.yaml