apiVersion: apps/v1
kind: Deployment
metadata:
    name: zaplink-consumer-service
    labels:
        app: zaplink-consumer-service
spec:
    replicas: 1
    selector:
        matchLabels:
            app: zaplink-consumer-service
    template:
        metadata:
            labels:
                app: zaplink-consumer-service
        spec:
            containers:
                - name: zaplink-consumer-service
                  image: zaplink-consumer-service:latest
                  imagePullPolicy: Never
                  ports:
                      - containerPort: 8082
                  env:
                      - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
                        value: "http://zaplink-service-registry:8761/eureka/"
                      - name: SPRING_PROFILES_ACTIVE
                        value: "k8s"
                      
                      # EXTERNAL Kafka access using dynamic IP
                      - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
                        value: "192.168.49.2:30092"
                      - name: KAFKA_NODE_IP
                        valueFrom:
                          fieldRef:
                            fieldPath: status.hostIP
                      
                      # INTERNAL Redis access (recommended for Kubernetes)
                      - name: SPRING_DATA_REDIS_HOST
                        value: "redis"
                      - name: SPRING_DATA_REDIS_PORT
                        value: "6379"
---
apiVersion: v1
kind: Service
metadata:
    name: zaplink-consumer-service
spec:
    type: NodePort
    selector:
        app: zaplink-consumer-service
    ports:
        - port: 8082
          targetPort: 8082
          nodePort: 30082
