# apiVersion: apps/v1
# kind: Deployment
# metadata:
#     name: zaplink-service-registry
#     labels:
#         app: zaplink-service-registry
# spec:
#     replicas: 1
#     selector:
#         matchLabels:
#             app: zaplink-service-registry
#     template:
#         metadata:
#             labels:
#                 app: zaplink-service-registry
#         spec:
#             containers:
#                 - name: zaplink-service-registry
#                   image: zaplink-service-registry:latest
#                   imagePullPolicy: Never
#                   ports:
#                       - containerPort: 8761
#                   env:
#                       - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
#                         value: "false"
#                       - name: EUREKA_CLIENT_FETCH_REGISTRY
#                         value: "false"
# ---
# apiVersion: v1
# kind: Service
# metadata:
#     name: zaplink-service-registry
# spec:
#     type: NodePort
#     selector:
#         app: zaplink-service-registry
#     ports:
#         - port: 8761
#           targetPort: 8761