apiVersion: apps/v1
kind: Deployment
metadata:
    name: zaplink-manager-service
    labels:
        app: zaplink-manager-service
spec:
    replicas: 1
    selector:
        matchLabels:
            app: zaplink-manager-service
    template:
        metadata:
            labels:
                app: zaplink-manager-service
        spec:
            containers:
                - name: zaplink-manager-service
                  image: zaplink-manager-service:latest
                  imagePullPolicy: Never
                  ports:
                      - containerPort: 8083
                  envFrom:
                    - configMapRef:
                        name: zaplink-config
                  env:
                      - name: SPRING_PROFILES_ACTIVE
                        value: "k8s"
                      
                      # INTERNAL Redis access (recommended for Kubernetes)
                      - name: SPRING_DATA_REDIS_HOST
                        value: "redis"
                      - name: SPRING_DATA_REDIS_PORT
                        value: "6379"
                        startupProbe:
                          httpGet:
                            path: /actuator/health/liveness
                            port: 8083
                          failureThreshold: 30
                          periodSeconds: 10

                        livenessProbe:
                          httpGet:
                            path: /actuator/health/liveness
                            port: 8083
                          initialDelaySeconds: 60
                          periodSeconds: 15

                        readinessProbe:
                          httpGet:
                            path: /actuator/health/readiness
                            port: 8083
                          initialDelaySeconds: 45
                          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
    name: zaplink-manager-service
spec:
    selector:
        app: zaplink-manager-service
    type: NodePort
    ports:
        - port: 8083
          targetPort: 8083
          nodePort: 30083