apiVersion: apps/v1
kind: Deployment
metadata:
    name: zaplink-manager-service
    labels:
        app: zaplink-manager-service
spec:
    replicas: 1
    selector:
        matchLabels:
            app: zaplink-manager-service
    template:
        metadata:
            labels:
                app: zaplink-manager-service
        spec:
            containers:
                - name: zaplink-manager-service
                  image: zaplink-manager-service:latest
                  imagePullPolicy: IfNotPresent
                  ports:
                      - containerPort: 8083
                  env:
                      - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
                        value: "http://zaplink-service-registry:8761/eureka/"
                      - name: SPRING_PROFILES_ACTIVE
                        value: "k8s"
                      - name: SPRING_DATA_REDIS_HOST
                        value: "redis"
                      - name: SPRING_DATA_REDIS_PORT
                        value: "6379"
---
apiVersion: v1
kind: Service
metadata:
    name: zaplink-manager-service
spec:
    selector:
        app: zaplink-manager-service
    ports:
        - port: 8083
          targetPort: 8083
    type: ClusterIP
