apiVersion: apps/v1
kind: Deployment
metadata:
    name: zaplink-consumer-service
    labels:
        app: zaplink-consumer-service
spec:
    replicas: 1
    selector:
        matchLabels:
            app: zaplink-consumer-service
    template:
        metadata:
            labels:
                app: zaplink-consumer-service
        spec:
            containers:
                - name: zaplink-consumer-service
                  image: zaplink-consumer-service:latest
                  imagePullPolicy: IfNotPresent
                  ports:
                      - containerPort: 8082
                  env:
                      - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
                        value: "http://zaplink-service-registry:8761/eureka/"
                      - name: SPRING_PROFILES_ACTIVE
                        value: "k8s"
                      - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
                        value: "kafka.default.svc.cluster.local:9092"
---
apiVersion: v1
kind: Service
metadata:
    name: zaplink-consumer-service
spec:
    type: NodePort
    selector:
        app: zaplink-consumer-service
    ports:
        - port: 8082
          targetPort: 8082
          nodePort: 30082
