apiVersion: apps/v1
kind: Deployment
metadata:
  name: zaplink-shortner-service
  labels:
    app: zaplink-shortner-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zaplink-shortner-service
  template:
    metadata:
      labels:
        app: zaplink-shortner-service
    spec:
      containers:
        - name: zaplink-shortner-service
          image: zaplink-shortner-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: zaplink-config
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "k8s"
              startupProbe:
                httpGet:
                  path: /actuator/health/liveness
                  port: 8090
                failureThreshold: 30
                periodSeconds: 10

              livenessProbe:
                httpGet:
                  path: /actuator/health/liveness
                  port: 8090
                initialDelaySeconds: 60
                periodSeconds: 15

              readinessProbe:
                httpGet:
                  path: /actuator/health/readiness
                  port: 8090
                initialDelaySeconds: 45
                periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: zaplink-shortner-service
spec:
  selector:
    app: zaplink-shortner-service
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30081
