server:
    port: 8081
    servlet:
        context-path: /api/v1

spring:
    application:
        name: zaplink-producer-service
    # Redis configs
    data:
        redis:
            host: ${SPRING_DATA_REDIS_HOST:redis}
            port: ${SPRING_DATA_REDIS_PORT:6379}
    # Kafka config
    kafka:
        # bootstrap-servers: localhost:9092
        bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
            acks: all
            retries: 5
            properties:
                spring.json.add.type.headers: false

# SERVICE REGISTRY CONFIG
eureka:
    client:
        serviceUrl:
            defaultZone: http://zaplink-service-registry:8761/eureka/
            # defaultZone: http://localhost:8761/eureka/

# logging:
#     level:
#         org:
#             apache:
#                 kafka: DEBUG
