server:
    port: 8081
    servlet:
        context-path: /api/v1

spring:
    application:
        name: zaplink-producer-service
    # Redis configs
    redis:
        data:
            host: localhost
            port: 6379
    # Kafka config
    kafka:
        bootstrap-servers: localhost:9092
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

# SERVICE REGISTRY CONFIG
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/

# logging:
#     level:
#         org:
#             apache:
#                 kafka: DEBUG
