server:
  port: 8090

spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
          routes:
            - id: shortner
              uri: lb://zaplink-shortner-service
              predicates:
                - Path=/shortner/**
                - Method=POST,GET
            - id: processor
              uri: lb://zaplink-processor-service
              predicates:
                - Path=/processor/**
                - Method=POST,GET
              filters:
                - StripPrefix=1
            - id: manager
              uri: lb://zaplink-manager-service
              predicates:
                - Path=/manager/**
                - Method=POST,GET,DELETE
            - id: manager-short
              uri: lb://zaplink-manager-service
              predicates:
                - Path=/m/**
                - Method=POST,GET,DELETE
              filters:
                - RewritePath=/m/(?<segment>.*), /manager/${segment}
            - id: auth-service
              uri: lb://zaplink-auth-service
              predicates:
                - Path=/auth/**
                - Method=POST,GET,PUT
            - id: user-service
              uri: lb://zaplink-auth-service
              predicates:
                - Path=/users/**
                - Method=GET,PUT
      httpclient:
        connect-timeout: 3000
        response-timeout: 5s


management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
    redis:
      enabled: false
  prometheus:
    metrics:
      export:
        enabled: true
