spring:
  application:
    name: zaplink-manager-service
  servlet:
    context-path: /v1

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}
  
  # Database config
  datasource:
      url: jdbc:postgresql://localhost:5432/
      username: postgres
      password: rgbXYZ@09182
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8083