spring:
  application:
    name: zaplink-manager-service
  servlet:
    context-path: /v1

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}

server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://zaplink-service-registry:8761/eureka/
